# Cluster configuration for SLURM execution
# Usage: snakemake --cluster-config cluster_config.yaml --cluster "sbatch ..."

__default__:
  account: "research-ceg-wm"
  partition: "compute,memory"
  time: "2:00:00"
  mem: "8G"
  cpus: 1
  output: "logs/slurm/slurm_%j.out"
  error: "logs/slurm/slurm_%j.err"

fastp_qc:
  time: "6:10:00"
  mem: "128G"
  cpus: 24
  partition: "compute"

ribodetector_rrna_removal:
  time: "120:00:00"
  mem: "64G"
  cpus: 16
  partition: "compute,memory"

spades_assembly:
  time: "120:00:00"
  mem: "256G"
  cpus: 16
  partition: "compute,memory"

reformat_assemblies:
  time: "1:00:00"
  mem: "8G"
  cpus: 1
  partition: "compute"

esviritu_identification:
  time: "120:00:00"
  mem: "32G"
  cpus: 8
  partition: "compute,memory"

virbot_identification:
  time: "120:00:00"
  mem: "32G"
  cpus: 16
  partition: "compute,memory"

merge_esviritu_results:
  time: "1:00:00"
  mem: "16G"
  cpus: 1
  partition: "compute"